### ISSUE TITLE
`spin deploy` is using application name from the bindle rather than from the application manifest

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/cloud-plugin#21] opened 2023-04-26 17:34 UTC
https://github.com/fermyon/spin/blob/b1ac4d8307948bbcd833fc689be3471f8fa174a0/src/commands/deploy.rs#L231

This is a problem in the following scenario:
1. Change application name in `spin.toml`
2. Run `spin deploy`
3. Uses old name to find the app id when we expected it to use the new name

Although users will typically need to run `spin build` before deploying anyways, this is a subtle and confusing bug I think we should avoid.

CC @bacongobbler

**Comment by itowlson** [comment] 2023-10-11 22:40
Is this still needed now we are in the OCI world?  If so, what is the specific change that is being requested?

**Comment by calebschoepp** [comment] 2023-10-12 14:54
I don't know if this is fixed now that we're using OCI. It can be tested by:
1. Make an app with `spin new`
2. Run `spin build`
3. Run `spin cloud deploy`
4. Modify the name of the app in the `spin.toml`
5. Run `spin cloud deploy` again
6. Expect to see two different apps in the cloud with different names

If we don't see two different apps than the OCI deploy path is probably pulling the name from the OCI image (similar to how Bindle was doing it) which is a subtle behaviour we want to avoid.

**Comment by itowlson** [comment] 2023-10-12 19:22
I followed your steps and I have two different apps in the cloud with two different names.  If I understand your message correctly, that means the issue is fixed?

(I am a bit curious as to how Cloud could ever have "known" to use an old bindle/OCI image - there's no persistent ID, so it seems like that would require something to remember the old name somehow.  Oh or if it was matching on a hash derived from everything _except_ the `spin.toml`?!  Then again, no, I am not curious enough to dive back through months of bindle-related history.  I will be happier not knowing.)

Closing as fixed; if I've misunderstood, please re-open.

**Closed by itowlson** 2023-10-12 19:22 UTC
Labels: bug
